
on: 
  push:
    tags:
    - '*'

jobs:
  publish-openscad:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - name: Hello world action step
        id: hello
        uses: ./openscad/
        with:
          who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "./output.stl"
          # bodyFile: "body.md"
          token: ${{ secrets.GITHUB_TOKEN }}
